# Generated by Django 4.1.4 on 2022-12-11 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0003_alter_message_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='external_id',
            field=models.PositiveIntegerField(verbose_name='Внешний ID пользователя'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.TextField(verbose_name='Имя пользователя'),
        ),
    ]
